<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="precio" type="xs:decimal"/>
                                        <xs:element name="categoria" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required" /> 
                                    <xs:attribute name="disponibilidad" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="en stock"/>
                                                <xs:enumeration value="agotado"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="imagen" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="codigoUnico">
            <xs:selector xpath="productos/producto"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
</xs:schema>